# Generated by Django 6.0.4 on 2026-05-15 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Encomenda', 'verbose_name_plural': 'Encomendas'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mpesa_reference',
            new_name='paysuite_id',
        ),
        migrations.AddField(
            model_name='order',
            name='goal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('credit_card', 'Cartão de Crédito/Débito')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paysuite_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='packages.coachingpackage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhado'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
    ]
