# Generated by Django 6.0.4 on 2026-05-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_method',
        ),
    ]
