# Generated by Django 6.0.4 on 2026-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_remove_order_pay_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("paid", "Pago"),
                    ("failed", "Falhado"),
                    ("refunded", "Reembolsado"),
                    ("chargeback", "Chargeback"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
