# Generated by Django 6.0.4 on 2026-10-06 20:27
# Editado à mão: trocar Remove+Add por Rename, para preservar os valores
# já gravados em produção (a Debito Pay está a ser substituída pela iMali).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="paysuite_id",
            new_name="gateway_transaction_id",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="paysuite_transaction_id",
            new_name="gateway_reference",
        ),
    ]
