# Generated by Django 6.0.4 on 2026-04-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Nome do ícone (ex: 'bicep')", max_length=50)),
            ],
            options={
                'verbose_name': 'Grupo Muscular',
                'verbose_name_plural': 'Grupos Musculares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome (ex: Treino A)')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Dia da Semana')),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dia de Treino',
                'ordering': ['order', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('video', models.FileField(blank=True, null=True, upload_to='exercise_videos/', verbose_name='Vídeo')),
                ('video_url', models.URLField(blank=True, help_text='URL do vídeo (YouTube/Vimeo)', verbose_name='URL do Vídeo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='exercise_thumbnails/')),
                ('instructions', models.TextField(blank=True, verbose_name='Instruções de Execução')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('muscle_groups', models.ManyToManyField(related_name='exercises', to='workouts.musclegroup', verbose_name='Grupos Musculares')),
            ],
            options={
                'verbose_name': 'Exercício',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('sets', models.PositiveIntegerField(default=3, verbose_name='Séries')),
                ('reps', models.CharField(default='12', help_text='Ex: 12, 8-12, até falha', max_length=50, verbose_name='Repetições')),
                ('rest_seconds', models.PositiveIntegerField(default=60, verbose_name='Descanso (seg)')),
                ('tempo', models.CharField(blank=True, help_text='Ex: 3-1-2-0', max_length=20)),
                ('exercise_type', models.CharField(choices=[('normal', 'Normal'), ('superset', 'Superset'), ('dropset', 'Drop Set'), ('giant_set', 'Giant Set')], default='normal', max_length=20)),
                ('superset_group', models.PositiveIntegerField(blank=True, help_text='Agrupar exercícios do mesmo superset', null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutday')),
            ],
            options={
                'verbose_name': 'Exercício do Treino',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workoutday')),
            ],
            options={
                'verbose_name': 'Registro de Treino',
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField(verbose_name='Série #')),
                ('weight_kg', models.FloatField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('reps_done', models.PositiveIntegerField(blank=True, null=True, verbose_name='Reps realizadas')),
                ('completed', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workoutexercise')),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='workouts.workoutlog')),
            ],
            options={
                'verbose_name': 'Log de Exercício',
                'ordering': ['set_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Plano')),
                ('description', models.TextField(blank=True)),
                ('duration_weeks', models.PositiveIntegerField(default=4, verbose_name='Duração (semanas)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de Treino',
                'verbose_name_plural': 'Planos de Treino',
            },
        ),
        migrations.AddField(
            model_name='workoutday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workouts.workoutplan'),
        ),
    ]
