# Generated by Django 6.0.4 on 2026-04-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Alimento')),
                ('calories_per_100g', models.FloatField(verbose_name='Calorias/100g')),
                ('protein_per_100g', models.FloatField(verbose_name='Proteína/100g')),
                ('carbs_per_100g', models.FloatField(verbose_name='Carboidratos/100g')),
                ('fat_per_100g', models.FloatField(verbose_name='Gordura/100g')),
                ('fiber_per_100g', models.FloatField(default=0, verbose_name='Fibra/100g')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Alimento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Café da Manhã'), ('morning_snack', 'Lanche da Manhã'), ('lunch', 'Almoço'), ('afternoon_snack', 'Lanche da Tarde'), ('dinner', 'Jantar'), ('supper', 'Ceia'), ('pre_workout', 'Pré-Treino'), ('post_workout', 'Pós-Treino')], max_length=20, verbose_name='Tipo de Refeição')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nome personalizado')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Horário sugerido')),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.FloatField(verbose_name='Quantidade (g)')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.fooditem')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meal')),
            ],
            options={
                'verbose_name': 'Item da Refeição',
            },
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Plano')),
                ('description', models.TextField(blank=True)),
                ('target_calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorias Alvo')),
                ('target_protein', models.FloatField(blank=True, null=True, verbose_name='Proteína Alvo (g)')),
                ('target_carbs', models.FloatField(blank=True, null=True, verbose_name='Carboidratos Alvo (g)')),
                ('target_fat', models.FloatField(blank=True, null=True, verbose_name='Gordura Alvo (g)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano Alimentar',
                'verbose_name_plural': 'Planos Alimentares',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.nutritionplan'),
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.meal')),
            ],
            options={
                'verbose_name': 'Registro Alimentar',
                'unique_together': {('client', 'date', 'meal')},
            },
        ),
    ]
