# Generated by Django 6.0.4 on 2026-09-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={
                "ordering": ["day_of_week", "order"],
                "verbose_name": "Refeição",
                "verbose_name_plural": "Refeições",
            },
        ),
        migrations.AddField(
            model_name="meal",
            name="day_of_week",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Segunda"),
                    (2, "Terça"),
                    (3, "Quarta"),
                    (4, "Quinta"),
                    (5, "Sexta"),
                    (6, "Sábado"),
                    (7, "Domingo"),
                ],
                help_text="Deixa em branco para refeições disponíveis em qualquer dia (ex: lanche livre).",
                null=True,
                verbose_name="Dia da Semana",
            ),
        ),
    ]
