# Generated by Django 6.0.4 on 2026-09-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_order_status"),
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coachingpackage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Pacote de Coaching",
                "verbose_name_plural": "Pacotes de Coaching",
            },
        ),
        migrations.AddField(
            model_name="clientpackage",
            name="order",
            field=models.OneToOneField(
                blank=True,
                help_text="Encomenda que originou este acesso (para reembolsos/chargebacks cancelarem o acesso).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_package",
                to="billing.order",
            ),
        ),
    ]
